spring:
  datasource:
    url: "jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE"

graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
    pageTitle: GraphiQL
graphql:
  servlet:
    mapping: /graphql