server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/props,file:./,file:${java.io.tmpdir}/ax-cloud-test-props/
      #profile: "server, native"