across:
  development:
    active: true

server:
  port: 8001

management:
  endpoint:
    health:
      show-details: always
    mappings:
      enabled: true
    info:
      enabled: true
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

#spring:
#  config:
#    import: "optional:configserver:"
spring:
  cloud:
    config:
      profile: "client, development"
      name: myclient
  jmx:
    enabled: false