across:
  development:
    active: true

server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    config:
      name: myclient
  jmx:
    enabled: false