across:
  development:
    active: true

server:
  port: 8001

management:
  endpoint:
    health:
      show-details: always
    mappings:
      enabled: true
    info:
      enabled: true
    restart:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  config:
    import: "configserver:${location.of.server:http://localhost:8888}"
  cloud:
    config:
      name: myclient
  jmx:
    enabled: false