spring:
  application:
    name: Spring Boot Admin Server
  boot:
    admin:
      client:
        url: "http://localhost:8080"
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
  port: 8080
