spring.boot.admin.url: http://localhost:8080
management.security.enabled: false

endpoints:
  health:
    sensitive: false
  metrics:
    sensitive: false
  beans:
    sensitive: false
  restart:
    enabled: true
spring:
  application:
    name: Spring Boot Admin Server